package br.ufjf.caed.exemplo.model;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.HashMap;
import javax.swing.AbstractListModel;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import org.dianaframework.view.BusinessObjectsCollection;
import org.dianaframework.view.CollectionModel;

/**
 *
 * Abstract list model for br.ufjf.caed.exemplo.model.ColecaoNoticias objects;
 * Generated by Diana Framework. DO NOT EDIT!!!
 *
 */
public class ColecaoNoticiasListModel extends AbstractListModel implements ComboBoxModel, CollectionModel {
private List objects;

private br.ufjf.caed.exemplo.model.Noticia selected;

private BusinessObjectsCollection boc;
private JComponent list;
private HashMap<String, String> parameters = new HashMap();

    public ColecaoNoticiasListModel() {
        objects = new ArrayList();
    }

    public void setSelectedItem(int item) {
        if (objects.size() > 0)
            selected = (br.ufjf.caed.exemplo.model.Noticia)objects.get(item);
    }

    public void setSelectedItem(Object item) {
        int inc = 0;
        for (; inc < objects.size(); inc++) {
            if (item != null && ((br.ufjf.caed.exemplo.model.Noticia)objects.get(inc)).getTitulo().equals(item)) {
                selected = (br.ufjf.caed.exemplo.model.Noticia)objects.get(inc);
                break;
            }
        }
    }

    public Object getSelectedItem() {
        return selected == null ? "" : ((br.ufjf.caed.exemplo.model.Noticia)selected).getTitulo();
    }

    public Object getElementAt(int ind) {
        return selected == null ? "" : ((br.ufjf.caed.exemplo.model.Noticia)objects.get(ind)).getTitulo();
    }

    public int getSize() {
        return objects.size();
    }

    public void setBusinessObjectsCollection(BusinessObjectsCollection boc) {
        this.boc = boc;
    }

    public void setObjectsCollection(List objects) {
        this.objects = objects;
        if (objects != null && objects.size() > 0) {
            selected = (br.ufjf.caed.exemplo.model.Noticia)objects.get(0);
            setSelectedIndex(0);
        } else {
            selected = null;
        }
        ((JComboBox)list).updateUI();
    }

    public List getObjects() {
        return objects;
    }

    public void reload() {
        boc.setParameters(parameters);
        objects = boc.collection();
    }

    public Object getSelectedObject() {
        return selected;
    }

    public String getSelectedValue() {
        return selected == null ? "" : String.valueOf(((br.ufjf.caed.exemplo.model.Noticia)selected).getTitulo());
    }

    public Object getObjectAt(int index){
        return objects.get(index);
    }

    public void setObjects(List<Object[]> val) {
        this.objects = val;
    }

    public br.ufjf.caed.exemplo.model.Noticia getSelected() {
        return selected;
    }

    public void addObject(Object obj) {
        objects.add(obj);
    }

    public void removeAll() {
        objects.clear();
    }

    public Object removeObject(int index) {
        return null;
    }

    public Object removeObject(Object obj) {
        return objects.remove(obj);
    }

    public Object removeSelectedObject() {
        for (int inc = 0; inc < objects.size(); inc++) {
            if (objects.get(inc) == selected) {
                return objects.remove(inc);
            }
        }
        return null;
    }

    public void setSelectedObject(Object obj) {
        Iterator objs = objects.iterator();
        Object objcmp;
        while (objs.hasNext()) {
            objcmp = objs.next();
            if (((br.ufjf.caed.exemplo.model.Noticia)objcmp).getTitulo().equals(obj)) {
                selected = (br.ufjf.caed.exemplo.model.Noticia)objcmp;
                return;
            }
        }
        if (objects.size() > 0)
            selected = (br.ufjf.caed.exemplo.model.Noticia)objects.get(0);
    }

    public void setSelected(br.ufjf.caed.exemplo.model.Noticia val) {
        this.selected = val;
    }

    public BusinessObjectsCollection getBoc() {
        return boc;
    }

    public void setBoc(BusinessObjectsCollection val) {
        this.boc = val;
    }

    public void setUIReference(Object list) {
        this.list = (JComponent)list;
    }

    public JComponent getUIReference() {
        return list;
    }

    public List getSelectedObjects() {
        return null;
    }

    public void setColumnsOrder(int[] columnsOrder) {
    }

    private void setSelectedIndex(int item) {
        if (list instanceof JComboBox) {
            ActionListener[] al = ((JComboBox)list).getActionListeners();
            // Removing all listeners before set the selected index
            for (int inc = 0; inc < al.length; inc++)
                ((JComboBox)list).removeActionListener(al[inc]);
            ((JComboBox)list).setSelectedIndex(item);
            // Put again all listeners after set the selected index
            for (int inc = 0; inc < al.length; inc++)
                ((JComboBox)list).addActionListener(al[inc]);
        }
    }

    public void setParameters(HashMap<String, String> parameters) {
        this.parameters = parameters;
    }
    public HashMap<String, String> getParameters() {
        return parameters;
    }

    public void addParameter(String name, String value) {
        parameters.put(name, value);
    }

    public void sortByColumn(int column, boolean isAscent) {}

}
