package br.ufjf.caed.exemplo.model;

// Generated 12/12/2006 17:16:16 by Hibernate Tools 3.2.0.beta8

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UnidadeespacialId generated by hbm2java
 */
@Embeddable
public class UnidadeespacialId implements java.io.Serializable {

	// Fields    

	private int codInstituicao;

	private int codUnidadeespacial;

	// Constructors

	/** default constructor */
	public UnidadeespacialId() {
	}

	/** full constructor */
	public UnidadeespacialId(int codInstituicao, int codUnidadeespacial) {
		this.codInstituicao = codInstituicao;
		this.codUnidadeespacial = codUnidadeespacial;
	}

	// Property accessors

	@Column(name = "cod_instituicao", unique = false, nullable = false, insertable = true, updatable = true)
	public int getCodInstituicao() {
		return this.codInstituicao;
	}

	public void setCodInstituicao(int codInstituicao) {
		this.codInstituicao = codInstituicao;
	}

	@Column(name = "cod_unidadeespacial", unique = false, nullable = false, insertable = true, updatable = true)
	public int getCodUnidadeespacial() {
		return this.codUnidadeespacial;
	}

	public void setCodUnidadeespacial(int codUnidadeespacial) {
		this.codUnidadeespacial = codUnidadeespacial;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UnidadeespacialId))
			return false;
		UnidadeespacialId castOther = (UnidadeespacialId) other;

		return (this.getCodInstituicao() == castOther.getCodInstituicao())
				&& (this.getCodUnidadeespacial() == castOther
						.getCodUnidadeespacial());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodInstituicao();
		result = 37 * result + this.getCodUnidadeespacial();
		return result;
	}

}
