/*
 * jdlgTesteCombos.java
 *
 * Created on 7 de Dezembro de 2006, 19:19
 */

package br.ufjf.caed.exemplo.view;

/**
 * 
 * Exemplo do CAEd Framework.
 * 
 * @version $Id:$
 * @author <a href="mailto:aryjunior@gmail.com">Ary Junior</a>
 *
 * @dianaframework.view
 *  name="TesteCombos"
 *  title="Teste com Combos"
 *  actions-package="br.ufjf.caed.exemplo.action.teste"
 *  collections-package="br.ufjf.caed.exemplo.model.teste"
 *
 */
public class jdlgTesteCombos extends javax.swing.JDialog {
    
    /** Creates new form jdlgTesteCombos */
    public jdlgTesteCombos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        btngrpOpcoes = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcmbxNivel1 = new javax.swing.JComboBox();
        jcmbxNivel2 = new javax.swing.JComboBox();
        jbtnFechar = new javax.swing.JButton();
        jrdbtnOpcao1 = new javax.swing.JRadioButton();
        jrdbtnOpcao2 = new javax.swing.JRadioButton();
        jrdbtnOpcao3 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jcmbxJornalistas = new javax.swing.JComboBox();
        jchkTeste = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jcmbxNivel3 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabel1.setText("N\u00edvel 1");

        jLabel2.setText("N\u00edvel 2");

        jLabel3.setText("N\u00edvel 3");

        jcmbxNivel1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcmbxNivel2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbtnFechar.setText("Fechar");

        btngrpOpcoes.add(jrdbtnOpcao1);
        jrdbtnOpcao1.setText("Op\u00e7\u00e3o 1");
        jrdbtnOpcao1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrdbtnOpcao1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jrdbtnOpcao1.setName("opcao1");

        btngrpOpcoes.add(jrdbtnOpcao2);
        jrdbtnOpcao2.setText("Op\u00e7\u00e3o 2");
        jrdbtnOpcao2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrdbtnOpcao2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jrdbtnOpcao2.setName("opcao2");

        btngrpOpcoes.add(jrdbtnOpcao3);
        jrdbtnOpcao3.setText("Op\u00e7\u00e3o 3");
        jrdbtnOpcao3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrdbtnOpcao3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jrdbtnOpcao3.setName("opcao3");

        jLabel4.setText("Teste com objetos no combo");

        jcmbxJornalistas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jchkTeste.setText("S\u00f3 para testar");
        jchkTeste.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jchkTeste.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jcmbxNivel3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jcmbxNivel3);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jcmbxNivel1, 0, 272, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .add(jcmbxNivel2, 0, 272, Short.MAX_VALUE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jchkTeste)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 150, Short.MAX_VALUE)
                        .add(jbtnFechar))
                    .add(jrdbtnOpcao1)
                    .add(jrdbtnOpcao2)
                    .add(jrdbtnOpcao3)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jcmbxJornalistas, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jcmbxNivel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jcmbxNivel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jrdbtnOpcao1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jrdbtnOpcao2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jrdbtnOpcao3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jcmbxJornalistas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jbtnFechar)
                    .add(jchkTeste))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jdlgTesteCombos(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }

    /**
     *
     * @dianaframework.action
     *  name="closeView"
     *
     */
    public javax.swing.JButton getJbtnFechar() {
        return jbtnFechar;
    }

    /**
     *
     * @dianaframework.form-field
     *  model="NiveisTesteCombo"
     *  selection-action="PreencheNivel2"
     *
     */
    public javax.swing.JComboBox getJcmbxNivel1() {
        return jcmbxNivel1;
    }

    /**
     *
     * @dianaframework.form-field
     *  model="Empty"
     *  selection-action="PreencheNivel3"
     *  reload="NO"
     *
     */
    public javax.swing.JComboBox getJcmbxNivel2() {
        return jcmbxNivel2;
    }

    /**
     *
     * @dianaframework.form-field
     *  model="Empty"
     *  reload="NO"
     *
     */
    public javax.swing.JList getJcmbxNivel3() {
        return jcmbxNivel3;
    }

    /**
     *
     * @dianaframework.form-field
     *
     */
    public javax.swing.ButtonGroup getBtngrpOpcoes() {
        return btngrpOpcoes;
    }

    /**
     *
     * @dianaframework.form-field
     *
     */
    public javax.swing.JRadioButton getJrdbtnOpcao1() {
        return jrdbtnOpcao1;
    }

    /**
     *
     * @dianaframework.form-field
     *
     */
    public javax.swing.JRadioButton getJrdbtnOpcao2() {
        return jrdbtnOpcao2;
    }

    /**
     *
     * @dianaframework.form-field
     *
     */
    public javax.swing.JRadioButton getJrdbtnOpcao3() {
        return jrdbtnOpcao3;
    }

    /**
     *
     * @dianaframework.form-field
     *  model="Empty"
     *  reload="NO"
     *
     */
    public javax.swing.JComboBox getJcmbxJornalistas() {
        return jcmbxJornalistas;
    }

    /**
     *
     * @dianaframework.form-field
     *
     */
    public javax.swing.JCheckBox getJchkTeste() {
        return jchkTeste;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngrpOpcoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtnFechar;
    private javax.swing.JCheckBox jchkTeste;
    private javax.swing.JComboBox jcmbxJornalistas;
    private javax.swing.JComboBox jcmbxNivel1;
    private javax.swing.JComboBox jcmbxNivel2;
    private javax.swing.JList jcmbxNivel3;
    private javax.swing.JRadioButton jrdbtnOpcao1;
    private javax.swing.JRadioButton jrdbtnOpcao2;
    private javax.swing.JRadioButton jrdbtnOpcao3;
    // End of variables declaration//GEN-END:variables
    
}
