/*
 * jdlgCadastroUnicoNoticia.java
 *
 * Created on 6 de Dezembro de 2006, 20:40
 */

package br.ufjf.caed.exemplo.view;

/**
 * 
 * Exemplo do CAEd Framework.
 * 
 * @version $Id:$
 * @author <a href="mailto:aryjunior@gmail.com">Ary Junior</a>
 *
 * @dianaframework.view
 *  name="CadastroNoticiasUnico"
 *  title="Cadastro Único de Notícias"
 *  actions-package="br.ufjf.caed.exemplo.action.teste"
 *  collections-package="br.ufjf.caed.exemplo.model.teste"
 *
 */
public class jdlgCadastroUnicoNoticia extends javax.swing.JDialog {
    
    /** Creates new form jdlgCadastroUnicoNoticia */
    public jdlgCadastroUnicoNoticia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtfldTituloNoticia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblNoticias = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jbtnRemover = new javax.swing.JButton();
        jbtnInserir = new javax.swing.JButton();
        jbtnFechar = new javax.swing.JButton();
        lblIdNoticia = new javax.swing.JLabel();
        jbtnSalvarTodas = new javax.swing.JButton();
        jbtnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabel1.setText("ID :");

        jLabel2.setText("T\u00edtulo :");

        jtxtfldTituloNoticia.setText("jTextField2");

        jtblNoticias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblNoticias);

        jLabel3.setText("As not\u00edcias s\u00e3o cadastradas de uma s\u00f3 vez apenas com os t\u00edtulos");

        jbtnRemover.setText("Remover");

        jbtnInserir.setText("Inserir");

        jbtnFechar.setText("Fechar");

        lblIdNoticia.setText("jLabel4");

        jbtnSalvarTodas.setText("Salvar todas");

        jbtnSalvar.setText("Salvar");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblIdNoticia)
                    .add(jtxtfldTituloNoticia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 320, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(267, Short.MAX_VALUE)
                .add(jbtnInserir)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jbtnSalvar)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jbtnRemover)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3)
                .addContainerGap(103, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 500, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .add(jbtnSalvarTodas)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jbtnFechar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(lblIdNoticia))
                .add(12, 12, 12)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jtxtfldTituloNoticia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jbtnRemover)
                    .add(jbtnSalvar)
                    .add(jbtnInserir))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 197, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jbtnFechar)
                    .add(jbtnSalvarTodas))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jdlgCadastroUnicoNoticia(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }

    /**
     *
     * @dianaframework.action
     *  name="RemoverNoticiaUnico"
     *
     */
    public javax.swing.JButton getJbtnRemover() {
        return jbtnRemover;
    }

    /**
     *
     * @dianaframework.action
     *  name="closeView"
     *
     */
    public javax.swing.JButton getJbtnFechar() {
        return jbtnFechar;
    }

    /**
     *
     * @dianaframework.action
     *  name="InserirNoticiaUnico"
     *
     */
    public javax.swing.JButton getJbtnInserir() {
        return jbtnInserir;
    }
    
    /**
     *
     * @dianaframework.table
     *  name="jtblNoticias"
     *  model="ColecaoNoticiasUnico"
     *  click-action="AlterarNoticiaUnico"
     *
     */
    public javax.swing.JTable getJtblNoticias() {
        return jtblNoticias;
    }

    /**
     *
     * @dianaframework.form-field
     *
     */
    public javax.swing.JTextField getJtxtfldTituloNoticia() {
        return jtxtfldTituloNoticia;
    }

    /**
     *
     * @dianaframework.form-field
     *
     */
    public javax.swing.JLabel getLblIdNoticia() {
        return lblIdNoticia;
    }

    /**
     *
     * @dianaframework.action
     *  name="SalvarNoticiasUnico"
     *
     */
    public javax.swing.JButton getJbtnSalvarTodas() {
        return jbtnSalvarTodas;
    }

    /**
     *
     * @dianaframework.action
     *  name="AtualizarNoticiaUnico"
     *
     */
    public javax.swing.JButton getJbtnSalvar() {
        return jbtnSalvar;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnFechar;
    private javax.swing.JButton jbtnInserir;
    private javax.swing.JButton jbtnRemover;
    private javax.swing.JButton jbtnSalvar;
    private javax.swing.JButton jbtnSalvarTodas;
    private javax.swing.JTable jtblNoticias;
    private javax.swing.JTextField jtxtfldTituloNoticia;
    private javax.swing.JLabel lblIdNoticia;
    // End of variables declaration//GEN-END:variables
    
}
