/*
 * jdlgTesteGeracaoActions.java
 *
 * Created on 12 de Janeiro de 2007, 20:27
 */

package br.ufjf.caed.exemplo.view;

/**
 * 
 * Exemplo do CAEd Framework.
 * 
 * @version $Id:$
 * @author <a href="mailto:aryjunior@gmail.com">Ary Junior</a>
 *
 * @dianaframework.view
 *  name="TesteGeracaoActions"
 *  title="Teste com a geração automática de Actions"
 *  actions-package="br.ufjf.caed.exemplo.action.teste"
 *  collections-package="br.ufjf.caed.exemplo.model.teste"
 *
 */
public class jdlgTesteGeracaoActions extends javax.swing.JDialog {
    
    /** Creates new form jdlgTesteGeracaoActions */
    public jdlgTesteGeracaoActions(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jbtnTesteAction = new javax.swing.JButton();
        jlblTesteAction = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jbtnTesteAction.setText("Testar");

        jlblTesteAction.setText("jLabel1");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .add(jbtnTesteAction)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jlblTesteAction)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jlblTesteAction)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 82, Short.MAX_VALUE)
                .add(jbtnTesteAction)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jdlgTesteGeracaoActions(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }

    /**
     *
     * @dianaframework.action
     *  name="ActionGeradaParaTeste"
     *
     */
    public javax.swing.JButton getJbtnTesteAction() {
        return jbtnTesteAction;
    }

    /**
     *
     * @dianaframework.form-field
     *
     */
    public javax.swing.JLabel getJlblTesteAction() {
        return jlblTesteAction;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnTesteAction;
    private javax.swing.JLabel jlblTesteAction;
    // End of variables declaration//GEN-END:variables
    
}
