/*
 * jdlgManterCadastroNoticia.java
 *
 * Created on 30 de Novembro de 2006, 19:14
 */

package br.ufjf.caed.exemplo.view;

/**
 * 
 * Exemplo do CAEd Framework.
 * 
 * @version $Id:$
 * @author <a href="mailto:aryjunior@gmail.com">Ary Junior</a>
 *
 * @dianaframework.view
 *  name="ManterCadastroNoticia"
 *  title="Manter Cadastro de Notícias"
 *  actions-package="br.ufjf.caed.exemplo.action.teste"
 *  collections-package="br.ufjf.caed.exemplo.model.teste"
 *
 */
public class jdlgManterCadastroNoticia extends javax.swing.JDialog {
    
    /** Creates new form jdlgManterCadastroNoticia */
    public jdlgManterCadastroNoticia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        bgpOpcao = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jtxtfldIdNoticia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtfldTituloNoticia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtaConteudoNoticia = new javax.swing.JTextArea();
        jbtnCancelar = new javax.swing.JButton();
        jbtnSalvar = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jtxtJornais = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtDataPublicacao = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jcmbxUF = new javax.swing.JComboBox();
        chkPublicada = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabel1.setText("ID :");

        jtxtfldIdNoticia.setEditable(false);
        jtxtfldIdNoticia.setText("jTextField1");

        jLabel2.setText("T\u00edtulo :");

        jtxtfldTituloNoticia.setText("jTextField2");

        jLabel3.setText("Conte\u00fado :");

        jtxtaConteudoNoticia.setColumns(20);
        jtxtaConteudoNoticia.setRows(5);
        jScrollPane1.setViewportView(jtxtaConteudoNoticia);

        jbtnCancelar.setText("Cancelar");

        jbtnSalvar.setText("Salvar");

        bgpOpcao.add(jRadioButton1);
        jRadioButton1.setText("Op\u00e7\u00e3o A");
        jRadioButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton1.setName("a");

        bgpOpcao.add(jRadioButton2);
        jRadioButton2.setText("Op\u00e7\u00e3o B");
        jRadioButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton2.setName("b");

        jLabel4.setText("Em quantos jornais a not\u00edcia foi publicada:");

        jtxtJornais.setText("jTextField1");

        jLabel5.setText("Data publica\u00e7\u00e3o:");

        jLabel6.setText("UF:");

        jcmbxUF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        chkPublicada.setText("Publicada");
        chkPublicada.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkPublicada.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jtxtfldIdNoticia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jtxtfldTituloNoticia, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(jRadioButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jRadioButton2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 178, Short.MAX_VALUE)
                        .add(chkPublicada))
                    .add(jLabel3)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jbtnSalvar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtnCancelar))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(layout.createSequentialGroup()
                                .add(jLabel5)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jtxtDataPublicacao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel6)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jcmbxUF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jtxtJornais, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jtxtfldIdNoticia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jtxtfldTituloNoticia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButton1)
                    .add(jRadioButton2)
                    .add(chkPublicada))
                .add(10, 10, 10)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jtxtDataPublicacao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6)
                    .add(jcmbxUF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jtxtJornais, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 156, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jbtnCancelar)
                    .add(jbtnSalvar))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jdlgManterCadastroNoticia(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }

    /**
     *
     * @dianaframework.action
     *  name="closeView"
     *
     */
    public javax.swing.JButton getJbtnCancelar() {
        return jbtnCancelar;
    }

    /**
     *
     * @dianaframework.action
     *  name="SalvarNoticia"
     *
     */
    public javax.swing.JButton getJbtnSalvar() {
        return jbtnSalvar;
    }

    /**
     *
     * @dianaframework.form-field
     *
     */
    public javax.swing.JTextArea getJtxtaConteudoNoticia() {
        return jtxtaConteudoNoticia;
    }

    /**
     *
     * @dianaframework.form-field
     *
     */
    public javax.swing.JTextField getJtxtfldIdNoticia() {
        return jtxtfldIdNoticia;
    }

    /**
     *
     * @dianaframework.form-field
     *
     */
    public javax.swing.JTextField getJtxtfldTituloNoticia() {
        return jtxtfldTituloNoticia;
    }

    /**
     *
     * @dianaframework.form-field
     *
     */
    public javax.swing.ButtonGroup getBgpOpcao() {
        return bgpOpcao;
    }

    /**
     *
     * @dianaframework.form-field
     *
     */
    public javax.swing.JTextField getJtxtJornais() {
        return jtxtJornais;
    }

    /**
     *
     * @dianaframework.form-field
     *  type="DATE"
     *
     */
    public javax.swing.JFormattedTextField getJtxtDataPublicacao() {
        return jtxtDataPublicacao;
    }

    /**
     *
     * @dianaframework.form-field
     *  model="ColecaoUFs"
     *
     */
    public javax.swing.JComboBox getJcmbxUF() {
        return jcmbxUF;
    }

    /**
     *
     * @dianaframework.form-field
     *
     */
    public javax.swing.JCheckBox getChkPublicada() {
        return chkPublicada;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgpOpcao;
    private javax.swing.JCheckBox chkPublicada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnSalvar;
    private javax.swing.JComboBox jcmbxUF;
    private javax.swing.JFormattedTextField jtxtDataPublicacao;
    private javax.swing.JTextField jtxtJornais;
    private javax.swing.JTextArea jtxtaConteudoNoticia;
    private javax.swing.JTextField jtxtfldIdNoticia;
    private javax.swing.JTextField jtxtfldTituloNoticia;
    // End of variables declaration//GEN-END:variables
    
}
