/*
 * jdlgNoticias.java
 *
 * Created on 29 de Novembro de 2006, 20:08
 */

package br.ufjf.caed.exemplo.view;

/**
 * 
 * Exemplo do CAEd Framework.
 * 
 * @version $Id:$
 * @author <a href="mailto:aryjunior@gmail.com">Ary Junior</a>
 *
 * @dianaframework.view
 *  name="NoticiasCadastradas"
 *  title="Notícias Cadastradas"
 *  actions-package="br.ufjf.caed.exemplo.action.teste"
 *  collections-package="br.ufjf.caed.exemplo.model.teste"
 *
 */
public class jdlgNoticias extends javax.swing.JDialog {
    
    /** Creates new form jdlgNoticias */
    public jdlgNoticias(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcmbxCampo = new javax.swing.JComboBox();
        jtxtfldPalavraChave = new javax.swing.JTextField();
        jbtnPesquisar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jcmbxJornalistas = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblNoticias = new javax.swing.JTable();
        jbtnFechar = new javax.swing.JButton();
        jbtnExcluir = new javax.swing.JButton();
        jbtnAlterar = new javax.swing.JButton();
        jbtnIncluir = new javax.swing.JButton();
        jbtnConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));
        jLabel1.setText("Campo :");

        jLabel2.setText("Palavra Chave :");

        jcmbxCampo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jtxtfldPalavraChave.setText("jTextField1");

        jbtnPesquisar.setText("Pesquisar");

        jLabel3.setText("O campo abaixo \u00e9 um exemplo de combos com valores do BD");

        jcmbxJornalistas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Jornalista :");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jcmbxCampo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jtxtfldPalavraChave, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
                    .add(jbtnPesquisar)
                    .add(jLabel3)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jcmbxJornalistas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jcmbxCampo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .add(10, 10, 10)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(1, 1, 1)
                        .add(jtxtfldPalavraChave, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jbtnPesquisar)
                .add(16, 16, 16)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jcmbxJornalistas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jtblNoticias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblNoticias);

        jbtnFechar.setText("Fechar");

        jbtnExcluir.setText("Excluir");

        jbtnAlterar.setText("Alterar");

        jbtnIncluir.setText("Incluir");

        jbtnConsultar.setText("Consultar");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jbtnIncluir)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtnAlterar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtnConsultar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtnExcluir)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtnFechar))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 197, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jbtnFechar)
                    .add(jbtnExcluir)
                    .add(jbtnConsultar)
                    .add(jbtnAlterar)
                    .add(jbtnIncluir))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jdlgNoticias(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }

    /**
     *
     * @dianaframework.action
     *  name="RegistroNoticia"
     *  params="acao=alterar"
     *
     */
    public javax.swing.JButton getJbtnAlterar() {
        return jbtnAlterar;
    }

    /**
     *
     * @dianaframework.action
     *  name="ExcluirNoticia"
     *
     */
    public javax.swing.JButton getJbtnExcluir() {
        return jbtnExcluir;
    }

    /**
     *
     * @dianaframework.action
     *  name="closeView"
     *
     */
    public javax.swing.JButton getJbtnFechar() {
        return jbtnFechar;
    }

    /**
     *
     * @dianaframework.action
     *  name="RegistroNoticia"
     *  params="acao=incluir"
     *
     */
    public javax.swing.JButton getJbtnIncluir() {
        return jbtnIncluir;
    }

    /**
     *
     * @dianaframework.action
     *  name="PesquisarNoticias"
     *
     */
    public javax.swing.JButton getJbtnPesquisar() {
        return jbtnPesquisar;
    }

    /**
     *
     * @dianaframework.form-field
     *  model="CamposNoticia"
     *
     */
    public javax.swing.JComboBox getJcmbxCampo() {
        return jcmbxCampo;
    }
    
    /**
     *
     * @dianaframework.table
     *  name="jtblNoticias"
     *  model="ColecaoNoticias"
     *  double-click-action="AlterarNoticia"
     *
     */
    public javax.swing.JTable getJtblNoticias() {
        return jtblNoticias;
    }

    /**
     *
     * @dianaframework.form-field
     *
     */
    public javax.swing.JTextField getJtxtfldPalavraChave() {
        return jtxtfldPalavraChave;
    }

    /**
     *
     * @dianaframework.action
     *  name="ConsultarNoticia"
     *
     */
    public javax.swing.JButton getJbtnConsultar() {
        return jbtnConsultar;
    }

    /**
     *
     * @dianaframework.form-field
     *  model="ColecaoJornalistas"
     *  selection-action="FiltrarNoticias"
     *
     */
    public javax.swing.JComboBox getJcmbxJornalistas() {
        return jcmbxJornalistas;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAlterar;
    private javax.swing.JButton jbtnConsultar;
    private javax.swing.JButton jbtnExcluir;
    private javax.swing.JButton jbtnFechar;
    private javax.swing.JButton jbtnIncluir;
    private javax.swing.JButton jbtnPesquisar;
    private javax.swing.JComboBox jcmbxCampo;
    private javax.swing.JComboBox jcmbxJornalistas;
    private javax.swing.JTable jtblNoticias;
    private javax.swing.JTextField jtxtfldPalavraChave;
    // End of variables declaration//GEN-END:variables
    
}
