package br.ufjf.caed.exemplo;

import org.dianaframework.servicelocator.BusinessService;
import org.dianaframework.model.GenericDAO;

/**
 *
 * Base business service for br.ufjf.caed.exemplo.ExemploBS.
 * Generated by Diana Framework. DO NOT EDIT!!!
 *
 */
public class ExemploBSBaseBS extends BusinessService {
protected GenericDAO daoNoticia;
protected GenericDAO daoJornalista;

public GenericDAO getDaoNoticia() {
    return daoNoticia;
}

public void setDaoNoticia(GenericDAO daoNoticia) {
    this.daoNoticia = daoNoticia;
}

public GenericDAO getDaoJornalista() {
    return daoJornalista;
}

public void setDaoJornalista(GenericDAO daoJornalista) {
    this.daoJornalista = daoJornalista;
}

}
