package br.ufjf.caed.exemplo.action;

import java.util.Date;
import org.dianaframework.action.Action;

/**
 *
 * Base action for br.ufjf.caed.exemplo.action.SalvarNoticia.
 * Generated by Diana Framework. DO NOT EDIT!!!
 *
 */
public class SalvarNoticiaBaseAction extends Action {
    public String getjtxtfldTituloNoticia() {
    return getFormFieldValue("jtxtfldTituloNoticia").toString();
}

public String getjtxtaConteudoNoticia() {
    return getFormFieldValue("jtxtaConteudoNoticia").toString();
}

}
